kind: pipeline
name: default
# default build goes with: --network "carthagenet"
# integration test is using env variables:
# - FROM_BLOCK_HEADER - block hash,
# - TO_BLOCK_HEADER - block hash
# -- all headers in interval (FROM_BLOCK_HEADER, TO_BLOCK_HEADER> are checked in test (rpc json compare)
# - OCAML_NODE_RPC_CONTEXT_ROOT: running ocaml node, e.g.: http://ocaml-node-run:8732
# - TEZEDGE_NODE_RPC_CONTEXT_ROOT: running tezedge node, e.g.: http://tezedge-node-run:18732

steps:
# uncomment this step when a modification to the storage was done and requires a fresh bootstrap
# - name: cleanup-tezedge-data
#   image: alpine/git
#   user: root
#   volumes:
#     - name: tezedge-node-data
#       path: /tmp/tezedge_developer
#   commands:
#     - rm -rf /tmp/tezedge_developer/light-node
#     - rm -rf /tmp/tezedge_developer/tezos-node

- name: build-tezedge
  image: simplestakingcom/tezedge-ci-builder:latest
  user: root
  environment:
    SODIUM_USE_PKG_CONFIG: 1
  commands:
    - cargo build --release --workspace

- name: build-tezedge-master
  image: simplestakingcom/tezedge-ci-builder:latest
  user: root
  volumes:
    - name: cache
      path: /tmp/tezedge-cache
  environment:
    SODIUM_USE_PKG_CONFIG: 1
  commands:
    - cd /tmp/tezedge-cache
    - rm -rf tezedge
    - git clone https://github.com/simplestaking/tezedge.git && cd tezedge
    - cargo build --release --workspace

- name: tezedge-master-node-run
  image: simplestakingcom/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  detach: true
  volumes:
    - name: tezedge-master-node-data
      path: /tmp/tezedge_developer
    - name: cache
      path: /tmp/tezedge-cache
  environment:
    SODIUM_USE_PKG_CONFIG: 1
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts:./target/release
  commands: 
    - cd /tmp/tezedge-cache/tezedge
    - cargo run --release --bin light-node -- --config-file "./light_node/etc/tezedge/tezedge.config" --network "carthagenet" --protocol-runner "./target/release/protocol-runner" --p2p-port 39734 --websocket-address 0.0.0.0:34928 --rpc-port 28732 --tezos-data-dir=/tmp/tezedge_developer/tezos-node --bootstrap-db-path=/tmp/tezedge_developer/light-node

- name: tezedge-node-run
  image: simplestakingcom/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  detach: true
  volumes:
    - name: tezedge-node-data
      path: /tmp/tezedge_developer
  environment:
    SODIUM_USE_PKG_CONFIG: 1
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts:./target/release
  commands: 
    - cargo run --release --bin light-node -- --config-file "./light_node/etc/tezedge/tezedge.config" --network "carthagenet" --identity-file "/drone/src/docker/identities/identity_tezedge.json" --protocol-runner "./target/release/protocol-runner" --p2p-port 39733 --websocket-address 0.0.0.0:34927 --rpc-port 18732 --tezos-data-dir=/tmp/tezedge_developer/tezos-node --bootstrap-db-path=/tmp/tezedge_developer/light-node

- name: ocaml-node-run
  user: root
  image: tezos/tezos:carthagenet
  detach: true
  volumes:
    - name: ocaml-node-data
      path: /home/tezos/data
  commands:
    - cp /drone/src/docker/identities/identity_ocaml.json /home/tezos/data/identity.json
    - tezos-node run --rpc-addr 0.0.0.0 --net-addr 0.0.0.0:9734 --data-dir /home/tezos/data --history-mode archive --disable-testchain

- name: bootstrapping
  image: simplestakingcom/tezos-node-bootstrap:latest
  commands:
    - tezos-node-bootstrap --bootstrap

- name: wrk-performance-test
  image: simplestakingcom/tezos-node-bootstrap:wrk1
  pull: always
  user: root
  commands:
    - tezos-node-bootstrap --performance-test 

- name: tz-indexer-tezedge
  image: blockwatch/tzindex:latest
  user: root
  detach: true
  volumes:
    - name: indexer-tezedge-data
      path: /data
  environment:
    TZ_RPC_HOST: tezedge-node-run
    TZ_RPC_PORT: 18732
    TZ_SERVER_ADDR: 0.0.0.0
    TZ_SERVER_PORT: 8002
    TZ_SERVER_CORS_ENABLE: true
    TZ_DATABASE_PATH: /data/index
    TZ_SNAPSHOT_PATH: /data/snapshots

- name: tz-indexer-ocaml
  image: blockwatch/tzindex:latest
  user: root
  detach: true
  volumes:
    - name: indexer-ocaml-data
      path: /data
  environment:
    TZ_RPC_HOST: ocaml-node-run
    TZ_RPC_PORT: 8732
    TZ_SERVER_ADDR: 0.0.0.0
    TZ_SERVER_PORT: 8002
    TZ_SERVER_CORS_ENABLE: true
    TZ_DATABASE_PATH: /data/index
    TZ_SNAPSHOT_PATH: /data/snapshots

- name: indexer-test
  image: simplestakingcom/tezos-node-bootstrap:latest
  commands:
    - tezos-node-bootstrap --indexer-test

- name: test
  image: simplestakingcom/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
    OCAML_NODE_RPC_CONTEXT_ROOT: http://ocaml-node-run:8732
    TEZEDGE_NODE_RPC_CONTEXT_ROOT: http://tezedge-node-run:18732
    FROM_BLOCK_HEADER: BLockGenesisGenesisGenesisGenesisGenesisd6f5afWyME7
    TO_BLOCK_HEADER: BLR48VJKmrQys6az5KxkDhSksS7G98u59HX1Xq7vxkALXi5md7J
  commands:
    - cargo test --verbose --release -- --nocapture --ignored test_rpc_compare

volumes:
  - name: ocaml-node-data
    host:
      path: /etc/ocaml-node
  - name: tezedge-node-data
    host:
      path: /etc/tezedge-node
  - name: tezedge-master-node-data
    host:
      path: /etc/tezedge-master-node
  - name: cache
    host:
      path: /etc/tezedge-ci/cache
      
  - name: indexer-tezedge-data
    temp: {}
  - name: indexer-ocaml-data
    temp: {}

trigger:
  branch:
    - master

########################################################################################
---
kind: pipeline
name: carthage

environment:
  FROM_BLOCK_HEADER: 2
  TO_BLOCK_HEADER: 20000
  SODIUM_USE_PKG_CONFIG: 1
  LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts:./target/release

steps:
# uncomment this step when a modification to the storage was done and requires a fresh bootstrap
- name: cleanup-node-data
  image: alpine/git
  user: root
  volumes:
    - name: tezedge-node-data
      path: /tmp/tezedge_developer
    - name: ocaml-node-data
      path: /home/tezos/data
  commands:
    # tezedge data
    - rm -rf /tmp/tezedge_developer/light-node
    - rm -rf /tmp/tezedge_developer/tezos-node
    # ocaml data
    - rm -rf /home/tezos/data

- name: build-tezedge
  image: simplestakingcom/tezedge-ci-builder:latest
  user: root
  environment:
    SODIUM_USE_PKG_CONFIG: 1
  commands:
    - cargo build --release

- name: ocaml-node-run
  user: root
  image: tezos/tezos:carthagenet
  detach: true
  volumes:
    - name: ocaml-node-data
      path: /home/tezos/data
  commands:
    - cp /drone/src/docker/identities/identity_ocaml.json /home/tezos/data/identity.json
    - tezos-node run --rpc-addr 0.0.0.0 --net-addr 0.0.0.0:9734 --data-dir /home/tezos/data --history-mode archive --disable-testchain

- name: tezedge-node-run
  image: simplestakingcom/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  detach: true
  volumes:
    - name: tezedge-node-data
      path: /tmp/tezedge_developer
  commands: 
    - cargo run --release --bin light-node -- --config-file "./light_node/etc/tezedge/tezedge.config" --network "carthagenet" --identity-file "/drone/src/docker/identities/identity_tezedge.json" --protocol-runner "./target/release/protocol-runner" --p2p-port 39733 --websocket-address 0.0.0.0:34927 --rpc-port 18732 --tezos-data-dir=/tmp/tezedge_developer/tezos-node --bootstrap-db-path=/tmp/tezedge_developer/light-node

- name: bootstrapping
  image: simplestakingcom/tezos-node-bootstrap:level
  commands:
    - tezos-node-bootstrap --bootstrap $TO_BLOCK_HEADER

- name: rpc-integration-tests
  image: simplestakingcom/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  environment:
    RUST_BACKTRACE: 1
    OCAML_BUILD_CHAIN: remote
    OCAML_NODE_RPC_CONTEXT_ROOT: http://ocaml-node-run:8732
    TEZEDGE_NODE_RPC_CONTEXT_ROOT: http://tezedge-node-run:18732
  commands:
    - cargo test --verbose --release -- --nocapture --ignored test_rpc_compare

volumes:
  - name: ocaml-node-data
    host:
      path: /etc/carthage/ocaml-node
  - name: tezedge-node-data
    host:
      path: /etc/carthage/tezedge-node

trigger:
  branch:
    - feature/TE-99_TE-100